- name: Remove apache2
  apt: name=apache2 state=absent

- name: Ensure the PGP key is installed
  apt_key: >
    state=present
    id=AC40B2F7
    url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7"

- name: Ensure https support for apt is installed
  apt: >
    state=present
    pkg=apt-transport-https

- name: Ensure the passenger apt repository is added
  apt_repository: >
    state=present
    repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main'

- name: Ensure nginx is installed
  apt: >
    state=present
    pkg=nginx-full

- name: Ensure passenger is installed
  apt: >
    state=present
    pkg=passenger
    update_cache=yes

- name: Ensure the nginx configuration file is set
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Ensure nginx is running
  service: >
    name=nginx
    state=started

- name: Disable the default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
  - nginx reload

- name: Read passenger configuration
  register: passenger_root
  command: passenger-config --root
  changed_when: false

- name: Add passenger configuration
  template:
    src: passenger.conf.j2
    dest: /etc/nginx/conf.d/passenger.conf
  notify: nginx reload

- name: Add virtualhost configuration
  template:
    src: virtualhost.conf.j2
    dest: /etc/nginx/sites-available/{{ item.server_name }}
  with_items: virtual_hosts
  notify: nginx reload

- name: Disable virtualhosts
  file:
    path: /etc/nginx/sites-enabled/{{ item.server_name }}
    state: absent
  when: item.disabled is defined
  with_items: virtual_hosts
  notify: nginx reload

- name: Enable virtualhosts
  file:
    src: /etc/nginx/sites-available/{{ item.server_name }}
    dest: /etc/nginx/sites-enabled/{{ item.server_name }}
    state: link
  when: item.disabled is not defined
  with_items: virtual_hosts
  notify: nginx reload

