---
- name: Set firewall default policy
  sudo: yes
  ufw: state=enabled policy=reject

- name: Allow ssh
  sudo: yes
  ufw: rule=allow port={{ ssh.port }}

- name: Allow http
  sudo: yes
  ufw: rule=allow port={{ web.port }}

