---
- name: create source directory
  sudo: true
  shell: mkdir -p /usr/local/src creates=/usr/local/src

- name: clone ruby-install
  sudo: true
  git: repo=https://github.com/postmodern/ruby-install.git dest=/usr/local/src/ruby-install update=yes

- name: install ruby-install
  sudo: true
  command: make install chdir=/usr/local/src/ruby-install creates=/usr/local/bin/ruby-install

- name: install rubies
  sudo: true
  command: /usr/local/bin/ruby-install ruby {{ ruby.version }} creates={{ ruby.path }}

- name: install bundler
  sudo: true
  command: /opt/rubies/ruby-{{ ruby.version }}/bin/gem install bundler --no-user-install --no-document

