---
- name: install rails essential software via apt
  sudo: true
  apt: name={{ item.package }}
  with_items:
    - package: nodejs

- name: install rails
  command: "{{ ruby.path }}/bin/gem install rails --no-document"

- name: initialize rails directory
  file: path={{ rails.path }} state=directory owner={{ username }} group={{ username }}

- name: add rails template file
  template:
    src: rails_template.rb.j2
    dest: "{{ rails.path }}/rails_template.rb"

