---
- name: install rails essential software via apt
  sudo: true
  apt: name={{ item.package }}
  with_items:
    - package: nodejs
    - package: libpq-dev

- name: initialize rails directory
  file: path={{ rails.path }} state=directory owner={{ username }} group={{ username }}

- name: install rails
  command: "{{ ruby_path }}/bin/gem install rails --no-document"
