---
- hosts: all
  roles:
    - external/ackmann-dickenson.common

- hosts: webservers
  roles:
    - external/jdauphant.nginx
    - internal/ruby
    - internal/rails

- hosts: databases
  roles:
    - external/ANXS.postgresql
    - external/DavidWittman.redis

