---
- hosts: all
  roles:
    - internal/common

- hosts: webservers
  roles:
    - internal/web
    - internal/ruby
    - internal/rails

- hosts: databases
  roles:
    - external/ANXS.postgresql
    - external/DavidWittman.redis

