---
- name: update apt sources
  sudo: yes
  apt: update_cache=yes

- name: install rails essential software via apt
  sudo: true
  apt: name={{ item.package }}
  with_items:
    - package: nodejs

- name: install rails
  command: "{{ ruby.path }}/bin/gem install rails --no-document"

- name: add rails template file
  template:
    src: rails_template.rb.j2
    dest: "{{ rails.path }}/rails_template.rb"

- name: create new rails app from template
  command: chdir={{ rails.path }} {{ ruby.path }}/bin/rails new {{ rails.path }} -m {{ rails.path }}/rails_template.rb

- name: generate rails skeleton
  command: "{{ ruby.path }}/bin/bundle install chdir={{ rails.path }}"

- name: bundle install
  command: "{{ ruby.path }}/bin/bundle install chdir={{ rails.path }}"

